name: Build & Deploy API (win-x86 self-contained)

on:
  push: { branches: [ Develop ] }
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    env:
      PROJECT_FILE: Ecommerce.Service/Ecommerce.Service.csproj   # <-- AJÚSTALO
      PUBLISH_DIR: ./publish

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # RESTORE con el RID (clave para evitar NETSDK1047)
      - name: Restore (win-x86)
        run: dotnet restore "$env:PROJECT_FILE" -r win-x86

      # PUBLICAR self-contained x86 (plan 32-bit)
      - name: Publish (win-x86 self-contained)
        run: dotnet publish "$env:PROJECT_FILE" -c Release -r win-x86 --self-contained true -p:PublishReadyToRun=true -o "$env:PUBLISH_DIR"

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_764BAA611A3A49F18BD09EA1B37021F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_163F5A69C7634AE0A89DCC388C12AB3E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_826E0DEBDCC44418A74FEA412B9884CB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: EcommerseAPI
          slot-name: Production
          package: ./publish
